# Generated by Django 4.2.7 on 2024-03-08 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_date_alter_product_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 3, 8, 23, 44, 5, 578553)),
        ),
    ]
